# app/config/config.yml

liip_imagine :
  resolvers :
    default :
      web_path : ~

  filter_sets :
    cache : ~

    # the name of the "filter set"
    my_thumb :

      # adjust the image quality to 75%
      quality : 50

      # list of transformations to apply (the "filters")
      filters :

        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail  : { size : [384, 256], mode : outbound }



    my_view:

      quality: 85

      # list of transformations to apply (the "filters")
      filters:

        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [ 576, 384 ], mode: outbound }



    my_label:

      quality: 50

      # list of transformations to apply (the "filters")
      filters:

        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [ 46, 46 ] }

    my_front:

      quality: 75


