#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET

reset_filter:
  path: '/reset-filter'
  controller: App\Controller\HomeController::resetFilter
